language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - add-on
    - sys-img-armeabi-v7a-android-25

jdk:
  - oraclejdk8
os:
  - linux
script:
  - ./gradlew build connectedCheck